### PR TITLE
Updated proto for the App Restrictions Schema Change Push Notifications.

### PR DESCRIPTION
**Pull request by sergebeauchamp**
Change-Id: I62df458d65af76b425526c17cba1a9e890f67102

### CODE REVIEW

**Comment by pinhuachen-okta** [comment]
Hi, I'm trying to build this sample code, but getting this error. Seems like something added in this commit. Did I miss something?

main] [ERROR] protoc failed output: 
[main] [ERROR] protoc failed error: emm_pubsub.proto:126:35: Option "(datapol.semantic_type)" unknown.

**Comment by sigizmund** [comment]
Thanks for this report. We will take a look.

**Comment by sergebeauchamp** [comment]
Hello, 

Apologies for the inconvenience, I will submit another pull request shortly.

In the mean time, you can change the following line:

optional string product_id = 1 [(datapol.semantic_type) = ST_SOFTWARE_ID];

to:

optional string product_id;

Regards,

Serge.

On Jan 08, 2016, at 09:57 PM, pinhuachen-okta <notifications@github.com> wrote:

Hi, I'm trying to build this sample code, but getting this error. Seems like something added in this commit. Did I miss something?
main] [ERROR] protoc failed output: 
[main] [ERROR] protoc failed error: emm_pubsub.proto:126:35: Option "(datapol.semantic_type)" unknown.

**Comment by sergebeauchamp** [comment]
Hello, 

Apologies for the inconvenience, I will submit another pull request shortly.

In the mean time, you can change the following line:

optional string product_id = 1 [(datapol.semantic_type) = ST_SOFTWARE_ID];

to:

optional string product_id;

Regards,

Serge.

On Jan 08, 2016, at 10:10 PM, sigizmund <notifications@github.com> wrote:

Thanks for this report. We will take a look.

**Comment by pinhuachen-okta** [comment]
Thank you @sergebeauchamp @sigizmund for the quick response. That's really helpful!

**Comment by sergebeauchamp** [comment]
Note the correction should be:

optional string product_id = 1 [(datapol.semantic_type) = ST_SOFTWARE_ID];

to:

optional string product_id = 1;

Serge.

On Jan 08, 2016, at 10:33 PM, pinhuachen-okta <notifications@github.com> wrote:

Thank you @sergebeauchamp @sigizmund for the quick response. That's really helpful!

**Pull request merged**
